### ISSUE TITLE
Update hourly forecast table in "today" tab

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#1000]
### Description

See behavior described in #999.

### Acceptance criteria

- [ ] I mean, basically if tests for #999 are implemented and passing, this must also be done.

**Comment by colinmurphy01** [comment]
This is blocked by #971 (if today tab goes away, this becomes irrelevant... I think?)

**Comment by greg-does-weather** [comment]
I'm not sure if it becomes irrelevant or not, but it may have already been addressed in the "overnight" #1017 PR that Eric did.

**Comment by colinmurphy01** [comment]
@greg-does-weather how can I confirm that this is resolved?

**Comment by mgwalker** [comment]
Pretty much have to check Honolulu before about 10:30am ET. (Spoiler: it is not resolved)
